import json, sqlite3

# HTML Template Generator
def create_dashboard():
    try:
        with open('ai_report.json', 'r') as f:
            data = json.load(f)
    except:
        data = {"revenue_projected": 0, "content_generated": 0}

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Profit Master v12.1 Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ background: #f0f2f5; font-family: 'Segoe UI', sans-serif; }}
            .card {{ border: none; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 0; margin-bottom: 30px; }}
            .stat-val {{ font-size: 2.5rem; font-weight: bold; color: #2c3e50; }}
            .success-text {{ color: #2ecc71; }}
        </style>
    </head>
    <body>
        <div class="header text-center">
            <h1>🚀 Profit Master Supreme v12.1</h1>
            <p>Live AI Monetization Status</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card p-4 text-center">
                        <h3>💰 Projected Revenue</h3>
                        <div class="stat-val text-success">${data.get('revenue_projected', 0):.2f}</div>
                        <small>This Cycle</small>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 text-center">
                        <h3>📝 Content Created</h3>
                        <div class="stat-val">{data.get('content_generated', 0)}</div>
                        <small>Premium Articles</small>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card p-4 text-center">
                        <h3>⚡ System Health</h3>
                        <div class="stat-val success-text">100%</div>
                        <small>Operational</small>
                    </div>
                </div>
            </div>
            <div class="card p-4">
                <h4>Recent Activity Log</h4>
                <pre>{json.dumps(data, indent=2)}</pre>
            </div>
            <footer class="text-center mt-4 text-muted">
                Generated by Profit Master Auto-System
            </footer>
        </div>
    </body>
    </html>
    """
    
    with open('dashboard.html', 'w') as f:
        f.write(html)
    print("✅ Dashboard Generated")

if __name__ == "__main__":
    create_dashboard()
