import json, os

def create_dashboard():
    try:
        with open('ai_report.json', 'r') as f:
            data = json.load(f)
    except:
        data = {"revenue_projected": 0, "articles": []}

    # Generate Article List HTML
    article_html = ""
    for art in data.get('articles', []):
        article_html += f"""
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{art['topic']}</h5>
                    <p class="card-text text-success">Quality Score: {art['quality']}%</p>
                    <a href="articles/{art['filename']}" class="btn btn-primary">📖 Read Full Article</a>
                </div>
            </div>
        </div>
        """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Profit Master Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ background: #f8f9fa; }}
            .header {{ background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: white; padding: 50px 0; margin-bottom: 30px; }}
            .stat-card {{ border-left: 5px solid; }}
            .stat-rev {{ border-color: #2ecc71; }}
            .stat-art {{ border-color: #3498db; }}
        </style>
    </head>
    <body>
        <div class="header text-center">
            <h1>🚀 Profit Master v12.1</h1>
            <p>Full Content Management System</p>
        </div>
        <div class="container">
            <!-- STATS -->
            <div class="row mb-5">
                <div class="col-md-6">
                    <div class="card p-4 stat-card stat-rev shadow-sm">
                        <h3>💰 Projected Revenue</h3>
                        <h1 class="text-success">${data.get('revenue_projected', 0):.2f}</h1>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card p-4 stat-card stat-art shadow-sm">
                        <h3>📚 Articles Generated</h3>
                        <h1>{len(data.get('articles', []))}</h1>
                    </div>
                </div>
            </div>

            <!-- ARTICLES SECTION -->
            <h3 class="mb-4 border-bottom pb-2">📄 Latest AI-Generated Articles</h3>
            <div class="row">
                {article_html}
            </div>
            
            <footer class="text-center mt-5 py-4 text-muted">
                Generated by Profit Master Supreme
            </footer>
        </div>
    </body>
    </html>
    """
    
    with open('index.html', 'w') as f:
        f.write(html)

if __name__ == "__main__":
    create_dashboard()
